# GPU args
gpu: "1"
multi_gpu: null

# Test args
model_name: FLOT
seed: 1
batch_size: 1
pretrain: ./pretrained/FLOT_8192.pth
evaluate: True
resume: True
num_test: 1

# Data args
num_points: 8192
dataset: FT3D_s_test # FT3D_s_test or KITTI_s_test
data_root: /path/to/data





