# GPU args
gpu: "1"
multi_gpu: null

# Training args
model_name: FLOT
seed: 1
batch_size: 4
epochs: 500
learning_rate: 0.001
pretrain: null
weight_decay: 0.0001
evaluate: False
val_batch_size: 1

# Data args
num_points: 2048
dataset: KITTI_r_sv
data_root: /path/to/data







